services:
  - docker
before_script:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
script:
  - make
branches:
  only:
    - master
notifications:
  slack: form3:SLG0PifAeMC7xowWEt2rjFZn
env:
  global:
    - secure: ZrLRaRB2d4KfoIkpjfAlSxIXSUapCn7clOtFW1tQauQmanOguB/lqu7zv06W28U+pR8fPF1d+FAbNgxcxlehw9+/B1Csi/VUE45XvNizmuyA2WLKZhG7RZQJdwCvwySFnJHWl3bbn2m2YtYuAKgc80SKxi7jYvnq+TGLZBFtu/yHuR6OYeVilw2JaoPah2nUqJhbU5/x+738Y3MRmUHokO6eErIG4wx1xPy0AnIKsfsbnh3GG17QeF7WGI8L4bvFMGutBjf8X3AtHaveiwImWXmLeFrHwSVVpNhwO3rf2zyQnRWq4K3JDjRrgibuil2yLE51Ttuk5gjYgvISTnZBgsi9y1vVpR6D/Jm1F5T5xASnhsEjV/K2XU/0X8tUSW4lb/FCsck7IgP/6KUHc5cb3/HfhhVt+xz6XWaL9yCr2x8W68IbvyXgo1ao27xatHDZCXRgNhX3LpRXMnA8yP1Suv/VNuYyEVWe3rhGRCOsw2drzHP2fgFzbj67ZTO2fRk2zYPEaKixa2iC8zvEg7WNmQfTX2qunHzvmwyQUurOAKdJNCZEBufScysfem8131HvepGxUo25fvXwMZtxWrpoEUtv3wPiBDcp/Vubi29mWNclwmQFELbWhKp5Ko/zSwtymAVHYXsWrTBYO84pt20HtbiJXNJX51sTut1uRCTy76U=
    - secure: nx9sRLj8vH4e3YAVKX8rvacIwykHjBh9rfUbM0ddqB3MXYX9FFdjdQpX4ImHFfpKPH7jtRvz0Xp3rwiiUKQFORl1b6gv/6Hs1et6Z6nhKvUx7P5LX2cCrNf4T3pe3st2NgK7ptcYCVovroFPYel/jszglOaCxEiljfEVICq/gSBo3polFy7D23N/jByoboR821q6uCc305VngSNSLaGqm4m4e3tWBZSBpsGTqd0JpJaNwXfbEl56jOOy3WIS68Bn5QVFg2dxzmeu6xf7FM5eXBedJDIwohgQ90E/ydbGWJMHZBHc/96Q3CkTNC3M3WA9b0Xyzkfk1gmLBWwui67us18Ly3sPYiwplg5pmmm4RrAQA/0LCaGViMwyRomms14Vz83xL5EkA/vk4tMlS/o9Q3SoDWLVrIhJr5Y6CZGuI/ySpGPPihX6pKU464jYN0kouCZRwbsXCiKGwTWlAkCNKRGaz0xitAmEYAYBFF3LgoL1qIoxoE4YZJsIu1REPUa0Us2oREv61hByENmwiQ1z6eTLUKmt5TcBXxGMmyxhfKLDOP7ZOmeQ5y/voHR0bCtWMxNosC2whTxuXcEhYhpwI8rHx/Vi1x4eqU91K92UuNxvXzKQYBV8/Z+2v44R918O3+Jw2go9+ctemDy082WQnVmFNrxMCVreCQPGWUSGDHs=
    - secure: hZMbeBqrWeJ7111J//hc4yk8tdGLybjLWcu+3VDFpMEF9sAgj9PHhJBzYJoOgqh/ZYGfsWh1SBBNinFoXFibhY1qD4e35bctXDSFne9xBSuqYrCeW6pu8XcoGsWfv0Ij5mXW/ybVUq81ol4kJn+7cyNWSNFHQE9LzckGE2iqQLcp2zoH6MMJ8vvJYv+8AdiJ4Hh3dK+BYWW1SWLw4Z6krK77GrNRZoYUs8yUZd3kJ2A0by3CtMipH8vlWOb39OgkjyIy7A7rHGZtppwi2bwRayIhXxxJ4Q9ZhCFZ4FRnOB2wNtv7ovdUxscQrX/Fafyj5+YLydupYDh9vYemDM3wvscc03wMEw8NQFQ30IoIKkebqQyrHtRGsbLjJWpqycGWpchU8RXbTbCXFY6kZPZ7nJOfCQ4alDKsYGwB9F+pr7KIjPozoVqLjgeqzTPYEVa7aRuXrwENcnrWGo/ioMNLX+nOhAMdwVzhyEV2EQBR/xqVhubUNf/CVxw6msUf/ZdiS5fZIDsrMRuK72KpE3I+UE7iXDz9fAcBE8PUt/sFOxElZUr7rotI9rg3VJQxcHrUl4h2L04ANgIK+cDFqYbAk7CzBM62AzhogenyF2DHg5araiv8mS6McqtJre0FmNEcvbx+a/Gf71Itj/xRgxCKJ+yZzZq0R85djgDOGyiIW8c=
  matrix:
    - TERRAFORM_VERSION=0.11.14
    - TERRAFORM_VERSION=0.12.9
    - TERRAFORM_VERSION=0.12.10
    - TERRAFORM_VERSION=0.12.13
    - TERRAFORM_VERSION=0.12.17
